label: "Conversation Dev"
description: "Neural Conversation System Baseline Dev"

cell_size: 1000
attn_size: 1000
embedding_size: 620
bidir: True
cell_type: GRU

data_dir: data/DiaTest
max_len: 50
model_dir: models/S2S/DiaTest
max_train_size: 1000000

steps_per_checkpoint: 10000
steps_per_eval: 10000
score_function: corpus_bleu
keep_best: 1
max_to_keep: null

optimizer: adam
learning_rate: 0.0002
batch_size: 80
batch_mode: standard
read_ahead: 20
max_gradient_norm: 1.0
max_epochs: 5
learning_rate_decay_factor: 0.5
decay_every_n_epoch: 0.5

attention_type: global
final_state: last

weight_scale: 0.01

encoders:
  - name: en

decoders:
  - name: fr

orthogonal_init: True
